alter table authors drop foreign key FK6g6ireq6qd4nxohq9ldidxfin;
alter table authors drop foreign key FKn0hxm216uc0t0kqawwp9y22ym;
alter table comments drop foreign key FKmb9bc55qru1mpcrpqducqc7c;
alter table comments drop foreign key FKno8nuh8wsshumvkd8rpxvqnc4;
alter table story_tags drop foreign key FKmans33ijt0nf65t0sng2r848j;
alter table story_tags drop foreign key FKq9guid7swnjxwdpgxj3jo1rsi;
drop table if exists authors;
drop table if exists comments;
drop table if exists example_objects;
drop table if exists stories;
drop table if exists story_tags;
drop table if exists tags;
drop table if exists users;
create table authors (story_id bigint not null, user_id bigint not null, primary key (story_id, user_id)) engine=InnoDB;
create table comments (id bigint not null auto_increment, created date, enabled bit not null, modified date, points integer not null, text varchar(255) not null, story_id bigint, nested_comments bigint, primary key (id)) engine=InnoDB;
create table example_objects (id bigint not null auto_increment, optional varchar(255), required varchar(255) not null, primary key (id)) engine=InnoDB;
create table stories (id bigint not null auto_increment, created date, enabled bit not null, modified date, points integer not null, text varchar(255) not null, title varchar(255) not null, views integer not null, primary key (id)) engine=InnoDB;
create table story_tags (story_id bigint not null, tag_id bigint not null, primary key (story_id, tag_id)) engine=InnoDB;
create table tags (id bigint not null auto_increment, created date, enabled bit not null, modified date, name varchar(255) not null, primary key (id)) engine=InnoDB;
create table users (id bigint not null auto_increment, created date, email varchar(255) not null, enabled bit not null, firstName varchar(255) not null, lastName varchar(255) not null, modified date, password varchar(255) not null, points integer not null, username varchar(255) not null, primary key (id)) engine=InnoDB;
alter table users add constraint UK_6dotkott2kjsp8vw4d0m25fb7 unique (email);
alter table users add constraint UK_r43af9ap4edm43mmtq01oddj6 unique (username);
alter table authors add constraint FK6g6ireq6qd4nxohq9ldidxfin foreign key (user_id) references users (id);
alter table authors add constraint FKn0hxm216uc0t0kqawwp9y22ym foreign key (story_id) references stories (id);
alter table comments add constraint FKmb9bc55qru1mpcrpqducqc7c foreign key (story_id) references stories (id);
alter table comments add constraint FKno8nuh8wsshumvkd8rpxvqnc4 foreign key (nested_comments) references comments (id);
alter table story_tags add constraint FKmans33ijt0nf65t0sng2r848j foreign key (tag_id) references tags (id);
alter table story_tags add constraint FKq9guid7swnjxwdpgxj3jo1rsi foreign key (story_id) references stories (id);
