alter table comments drop foreign key FKmb9bc55qru1mpcrpqducqc7c;
alter table comments drop foreign key FK8omq0tc18jd43bu5tjh6jvraq;
alter table comments drop foreign key FKno8nuh8wsshumvkd8rpxvqnc4;
alter table ratings drop foreign key FKbqcpnd1ybxup1v2rw0t15cqat;
alter table ratings drop foreign key FKb3354ee2xxvdrbyq9f42jdayd;
alter table recommendation drop foreign key FKn4n4fbncuvh27fmccphff9ce8;
alter table recommendation drop foreign key FKrwu8ddeus85k2p40wlvojuw1v;
alter table stories drop foreign key FKa4ak6n0w5tjjxht2tky5iovmc;
drop table if exists comments;
drop table if exists ratings;
drop table if exists recommendation;
drop table if exists stories;
drop table if exists tags;
drop table if exists users;
create table comments (id bigint not null auto_increment, created datetime(6) not null, enabled bit not null, modified datetime(6), points integer not null, text varchar(255) not null, story_id bigint, user_id bigint, nested_comments bigint, primary key (id)) engine=InnoDB;
create table ratings (id bigint not null auto_increment, created datetime(6), enabled bit not null, modified datetime(6), rating double precision, story_id bigint, user_id bigint, primary key (id)) engine=InnoDB;
create table recommendation (id bigint not null auto_increment, created datetime(6), enabled bit not null, modified datetime(6), rating double precision not null, story_id bigint, user_id bigint, primary key (id)) engine=InnoDB;
create table stories (id bigint not null auto_increment, created datetime(6) not null, enabled bit not null, modified datetime(6) not null, points integer not null, text longtext not null, title varchar(255) not null, views integer not null, author_id bigint, primary key (id)) engine=InnoDB;
create table tags (id bigint not null auto_increment, created datetime(6), enabled bit not null, modified datetime(6), name varchar(255) not null, primary key (id)) engine=InnoDB;
create table users (id bigint not null auto_increment, created datetime(6) not null, email varchar(255) not null, enabled bit not null, first_name varchar(255) not null, last_name varchar(255) not null, modified datetime(6), password varchar(60) not null, points integer not null, username varchar(255) not null, primary key (id)) engine=InnoDB;
alter table users add constraint UK_6dotkott2kjsp8vw4d0m25fb7 unique (email);
alter table users add constraint UK_r43af9ap4edm43mmtq01oddj6 unique (username);
alter table comments add constraint FKmb9bc55qru1mpcrpqducqc7c foreign key (story_id) references stories (id);
alter table comments add constraint FK8omq0tc18jd43bu5tjh6jvraq foreign key (user_id) references users (id);
alter table comments add constraint FKno8nuh8wsshumvkd8rpxvqnc4 foreign key (nested_comments) references comments (id);
alter table ratings add constraint FKbqcpnd1ybxup1v2rw0t15cqat foreign key (story_id) references stories (id);
alter table ratings add constraint FKb3354ee2xxvdrbyq9f42jdayd foreign key (user_id) references users (id);
alter table recommendation add constraint FKn4n4fbncuvh27fmccphff9ce8 foreign key (story_id) references stories (id);
alter table recommendation add constraint FKrwu8ddeus85k2p40wlvojuw1v foreign key (user_id) references users (id);
alter table stories add constraint FKa4ak6n0w5tjjxht2tky5iovmc foreign key (author_id) references users (id);
